Factory/Models/Machine.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEngineerMachine = new HashSet<EngineerMachine>();
    }

    public int MachineId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<EngineerMachine> JoinEngineerMachine { get; set; }

    public bool isDuplicateEngineer(FactoryContext _db, int engineerId)
    {
      var engineers =  _db.EngineerMachines.Where(engineer => engineer.MachineId == this.MachineId).ToList();
      bool isDuplicate = false;
      foreach (var engineer in engineers)
      {
        if (engineerId == engineer.EngineerId)
        {
          isDuplicate = true;
        }
      }
      return isDuplicate;
    }
  }
}

Factory/Controllers/EngineersController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController: Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");;
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      if (MachineId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() {MachineId = MachineId, EngineerId = engineer.EngineerId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      Engineer foundEngineer = _db.Engineers
        .Include(engineer => engineer.JoinEngineerMachine)
        .ThenInclude(joinMachine => joinMachine.Machine)
        .FirstOrDefault(model => model.EngineerId == id);
      return View(foundEngineer);
    }

    public ActionResult Edit(int id)
    {
      Engineer foundEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(foundEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var foundEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(foundEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var foundEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(foundEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      int savedEngineer = joinEntry.EngineerId;
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = savedEngineer});
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      bool isDuplicate = engineer.isDuplicateMachine(_db, MachineId);
      if (MachineId !=0 && isDuplicate == false)
      {
        _db.EngineerMachines.Add(new EngineerMachine() {MachineId = MachineId, EngineerId = engineer.EngineerId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId});
    }
  }
}

Factory/Controllers/MachinesController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine Machine, int EngineerId)
    {
      _db.Machines.Add(Machine);
      _db.SaveChanges();
      if (EngineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() {EngineerId = EngineerId, MachineId = Machine.MachineId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Machine foundMachine = _db.Machines
        .Include(Machine => Machine.JoinEngineerMachine)
        .ThenInclude(joinEngineer => joinEngineer.Engineer)
        .FirstOrDefault(model => model.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(foundMachine);
    }

    public ActionResult Edit(int id)
    {
      var foundMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(foundMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine Machine, int EngineerId)
    {
      if (EngineerId !=0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() {EngineerId = EngineerId, MachineId = Machine.MachineId});        
      }
      _db.Entry(Machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Machine foundMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      return View(foundMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine foundMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      _db.Machines.Remove(foundMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine Machine, int EngineerId)
    {
      bool isDuplicate = Machine.isDuplicateEngineer(_db, EngineerId);
      if (EngineerId !=0 && isDuplicate == false)
      {
        _db.EngineerMachines.Add(new EngineerMachine() {EngineerId = EngineerId, MachineId = Machine.MachineId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = Machine.MachineId});
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      int savedMachine = joinEntry.MachineId;
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = savedMachine});
    }
  }
}

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Enter new machine</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Save" />
}

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Delete</h2>

<h4>Delete this machine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-danger" />
}

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr>
<h4><strong>@Html.DisplayNameFor(model => model.Name): </strong>@Html.DisplayFor(model => model.Name)</h4>

<hr>

<h4><strong><Machines:</strong> (@Model.JoinEngineerMachine.Count)</h4>
@if (Model.JoinEngineerMachine.Count == 0)
{
  <p>No Engineer is currently licensed to fix this machine</p>
}
else
{
  <ul>
    @foreach (var join in Model.JoinEngineerMachine)
    {
      @using (Html.BeginForm("DeleteEngineer", "Machines"))
      {
        <p>
          <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#Engineer_@(join.EngineerMachineId)">
            Delete
          </button>
          - @Html.ActionLink($"{join.Engineer.Name}", "Details", "Engineers", new {id = join.Engineer.EngineerId})
        </p>
        <!-- Modal -->
        <div class="modal fade" id="Engineer_@(join.EngineerMachineId)" tabindex="-1" aria-labelledby="EngineerLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="EngineerLabel_@(join.EngineerMachineId)">Delete @join.Engineer.Name</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p>Clicking delete will make this action final.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                @using (Html.BeginForm("DeleteEngineer", "Machines"))
                {
                  @Html.Hidden("joinId", @join.EngineerMachineId)
                  <input type="submit" value="Delete"  class="btn btn-danger"/>
                }
              </div>
            </div>
          </div>
        </div>
      }
    }
  </ul>
}

@using (Html.BeginForm("AddEngineer","Machines"))
{
  @Html.HiddenFor(model => model.MachineId)
  @Html.Label("Add Engineer")
  @Html.DropDownList("EngineerId", "Select Engineer")
  <input type="submit" value="add" />
}
<hr>

<p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId})</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit this machine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save"/>
}

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>

<h2>Machines</h2>

@if (@Model.Count == 0)
{
  <p>There are no machines in the system.</p>
}

<ul>
  @foreach (Machine machine in Model)
  {
    <li>@Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId})</li>
  }
</ul>

<p>@Html.ActionLink("Add machine", "Create")</p>